project:
  type: website
  output-dir: docs

website:
  title: YinYun's Blog
  site-url: "https://yinyunli.github.io/myBlog/"
  search: true 
  navbar:
    background: none
    left:
      - href: index.qmd
        text: 首頁
      - href: about.qmd
        text: 關於




format:
  html:
    theme:
      light: cosmo
      dark: darkly
    color-scheme: auto
    include-in-header: header.html
    css: styles.css
    toc: true
    html-math-method: mathjax
    theme-color: "#1a1a1a"