project:
  type: website
  output-dir: docs

website:
  title: YinYun's Blog
  site-url: "https://yinyunli.github.io/myBlog/"
  navbar:
    background: none
    left:
      - href: index.qmd
        text: 首頁
      - href: about.qmd
        text: 關於

format:
  html:
    theme:
      light: [cosmo, brand]
      dark: [darkly, brand]
    css: styles.css
    toc: true
    html-math-method: mathjax



